CREATE TABLE IF NOT EXISTS CARDS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    CARD_NUMBER BIGINT NOT NULL,
    CARD_TYPE VARCHAR(100) NOT NULL,
    TOTAL_LIMIT DECIMAL(2) NOT NULL,
    AMOUNT_USED DECIMAL(2) NOT NULL,
    AVAILABLE_AMOUNT DECIMAL(2) NOT NULL,
    CREATE_DATE DATE DEFAULT NULL
);

INSERT INTO CARDS (CUSTOMER_ID,CARD_NUMBER,CARD_TYPE,TOTAL_LIMIT,AMOUNT_USED,AVAILABLE_AMOUNT,CREATE_DATE)
VALUES (1,'4555876876534563','CREDIT',10000.00,3000.00,7000.00,CURDATE());