CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    MOBILE_NUMBER VARCHAR(100) NOT NULL,
    CREATE_DATE date DEFAULT NULL
);

INSERT INTO CUSTOMERS (NAME,EMAIL,MOBILE_NUMBER,CREATE_DATE) VALUES ('JUAN PEREZ','JUANPEREZ@GMAIL.COM','1167654352',CURDATE());