spring:
    application:
        name: loans
    profiles:
        active: default
    config:
        import: optional:configserver:http://34.68.15.122:8060/
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        database-plataform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
    h2:
        console:
            enabled: true
    rabbitmq:
        host: localhost
        password: root
        port: 5672
        username: root
        exchange-direct: customer.exchange.direct
        exchange-fanout: customer.exchange.fanout
        queue-loans: customer.queue.loans
        queue-cards: customer.queue.cards
        queue: customer.queue
        routingKey: customer.routingKey
    main:
        allow-bean-definition-overriding: true
    sleuth:
        sampler:
            percentage: 1
    zipkin:
        baseUrl: http://35.239.172.220:9411/
        sender:
            #type: rabbit
            type: web
        rabbitmq:
            queue: zipkin.queue
    kafka:
        topic: customer-events
        consumer:
            bootstrap-servers: localhost:9092
            key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            group-id: customer-events-listener-group
server:
    port: 8090

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        shutdown:
            enabled: true
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://34.134.82.29:8010/eureka/
info:
    app:
        name: Loans Microservice
        description: Bank Loans Application
        version: 1.0.0
