CREATE TABLE IF NOT EXISTS LOANS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    START_DATE DATE NOT NULL,
    LOAN_TYPE VARCHAR(100) NOT NULL,
    TOTAL DECIMAL(2) NOT NULL,
    AMOUNT_PAID DECIMAL(2) NOT NULL,
    OUTSTANDING_AMOUNT DECIMAL(2) NOT NULL,
    CREATE_DATE DATE DEFAULT NULL
);

INSERT INTO LOANS (ID,CUSTOMER_ID,START_DATE,LOAN_TYPE,TOTAL,AMOUNT_PAID,OUTSTANDING_AMOUNT,CREATE_DATE)
VALUES (1,1,'2022-04-22','HOME',20000.00,10000.00,10000.00,CURDATE());
INSERT INTO LOANS (ID,CUSTOMER_ID,START_DATE,LOAN_TYPE,TOTAL,AMOUNT_PAID,OUTSTANDING_AMOUNT,CREATE_DATE)
VALUES (2,1,'2022-04-22','VEHICLE',10000.00,3000.00,7000.00,CURDATE());
