spring:
    application:
        name: eurekaserver
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
    config:
        import: optional:configserver:http://localhost:8060
    sleuth:
        sampler:
            percentage: 1
    rabbitmq:
        host: localhost
        port: 5672
        username: root
        password: root
    zipkin:
        baseUrl: http://localhost:9411/
        sender:
            type: rabbit
        rabbitmq:
            queue: zipkin.queue