spring:
    application:
        name: eurekaserver
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
    config:
        import: optional:configserver:http://localhost:8060
