spring:
    application:
        name: accounts
    profiles:
        active: default
    config:
        import: optional:configserver:http://localhost:8060
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        database-plataform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
    h2:
        console:
            enabled: true
    rabbitmq:
        host: localhost
        password: guest
        port: 5672
        username: guest
        exchange: customer.exchange
        queue: customer.queue
        routingKey: customer.routingKey
    main:
        allow-bean-definition-overriding: true
server:
    port: 8070

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        shutdown:
            enabled: true
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8010/eureka/
info:
    app:
        name: Accounts Microservice
        description: Bank Accounts Application
        version: 1.0.0