CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    ACCOUNT_TYPE VARCHAR(100) NOT NULL,
    BRANCH_ADDRESS VARCHAR(200) NOT NULL,
    CREATE_DATE DATE DEFAULT NULL
);

INSERT INTO ACCOUNTS (CUSTOMER_ID,ACCOUNT_TYPE,BRANCH_ADDRESS,CREATE_DATE) VALUES (1,'CUENTA DE AHORRO','BULNES 758',CURDATE());