CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    ACCOUNT_TYPE VARCHAR(100) NOT NULL,
    BRANCH_ADDRESS VARCHAR(200) NOT NULL,
    CREATE_DATE DATE DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    MOBILE_NUMBER VARCHAR(100) NOT NULL,
    CREATE_DATE date DEFAULT NULL
);

INSERT INTO CUSTOMERS (ID,NAME,EMAIL,MOBILE_NUMBER,CREATE_DATE) VALUES (1,'JUAN PEREZ','JUANPEREZ@GMAIL.COM','1167654352',CURDATE());
INSERT INTO ACCOUNTS (ID,CUSTOMER_ID,ACCOUNT_TYPE,BRANCH_ADDRESS,CREATE_DATE) VALUES (1,1,'CUENTA DE AHORRO','BULNES 758',CURDATE());